from pathlib import Path
from html import escape

ROOT = Path(__file__).parent
ORIGIN = "https://praneethpogula09.github.io/routecraft-systems"
EMAIL = "praneethpogula09@gmail.com"
UPDATED = "30 September 2026"

NAV = [
    ("index.html", "Home", "home"),
    ("services.html", "Services", "services"),
    ("ai-voice-agents.html", "AI Voice", "voice"),
    ("web-development.html", "Web", "web"),
    ("about.html", "About", "about"),
    ("contact.html", "Contact", "contact"),
]


def header(current):
    links = "".join(
        f'<a href="{href}"' + (' aria-current="page"' if key == current else '') + f'>{label}</a>'
        for href, label, key in NAV
    )
    return f'''<a class="skip-link" href="#main">Skip to main content</a>
<div class="announcement">14-day AI Front Desk pilot · $750 · One focused inbound workflow</div>
<header class="site-header">
  <div class="container nav-wrap">
    <a class="brand" href="index.html" aria-label="RouteCraft Systems home">
      <span class="brand-mark" aria-hidden="true"></span>
      <span class="brand-copy">RouteCraft<small>Systems</small></span>
    </a>
    <button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-navigation" aria-label="Open navigation">Menu</button>
    <nav class="nav-links" id="site-navigation" aria-label="Primary navigation">
      {links}
      <a class="btn btn-primary btn-small" href="contact.html" data-event="nav_pilot_click">Check pilot fit</a>
    </nav>
  </div>
</header>'''


def footer():
    return f'''<section class="cta-band" aria-labelledby="cta-title">
  <div class="container">
    <div><h2 id="cta-title">Map the call. Route the next step.</h2><p>Start with one tightly scoped inbound workflow. Test it, inspect the exceptions, then decide whether production makes sense.</p></div>
    <a class="btn btn-dark" href="contact.html" data-event="footer_pilot_click">Start the pilot conversation</a>
  </div>
</section>
<footer class="site-footer">
  <div class="container">
    <div class="footer-grid">
      <div>
        <a class="brand" href="index.html"><span class="brand-mark" aria-hidden="true"></span><span class="brand-copy">RouteCraft<small>Systems</small></span></a>
        <p class="muted">Managed AI front desks and digital customer-intake systems for service businesses.</p>
      </div>
      <div><h3>Services</h3><ul><li><a href="ai-voice-agents.html">AI Voice Agents</a></li><li><a href="web-development.html">Web Development</a></li><li><a href="services.html#pilot">$750 Pilot</a></li></ul></div>
      <div><h3>Company</h3><ul><li><a href="about.html">About</a></li><li><a href="contact.html">Contact</a></li><li><a href="mailto:{EMAIL}" data-event="email_click">Email us</a></li></ul></div>
      <div><h3>Legal</h3><ul><li><a href="privacy.html">Privacy</a></li><li><a href="terms.html">Terms</a></li><li><a href="ai-voice-agents.html#disclosure">AI & recording disclosure</a></li></ul></div>
    </div>
    <div class="footer-bottom"><span>© <span data-year>2026</span> RouteCraft Systems. Based in India, serving international clients.</span><span>No guaranteed bookings, revenue, uptime, or business outcomes.</span></div>
  </div>
</footer>'''


def page(name, title, description, current, body, noindex=False):
    canonical = f"{ORIGIN}/" if name == "index.html" else f"{ORIGIN}/{name}"
    robots = '<meta name="robots" content="noindex,nofollow">' if noindex else ''
    schema = f'''<script type="application/ld+json">{{
      "@context":"https://schema.org","@type":"ProfessionalService","name":"RouteCraft Systems",
      "url":"{ORIGIN}/","email":"{EMAIL}","founder":{{"@type":"Person","name":"Praneeth Pogula"}},
      "areaServed":["United States","Canada","Australia"],
      "description":"Managed AI front desks, websites, and customer-intake integrations for service businesses."
    }}</script>'''
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)}</title>
  <meta name="description" content="{escape(description, quote=True)}">
  {robots}
  <link rel="canonical" href="{canonical}">
  <meta property="og:type" content="website"><meta property="og:site_name" content="RouteCraft Systems">
  <meta property="og:title" content="{escape(title, quote=True)}"><meta property="og:description" content="{escape(description, quote=True)}"><meta property="og:url" content="{canonical}">
  <meta name="twitter:card" content="summary"><meta name="theme-color" content="#111712">
  <link rel="stylesheet" href="assets/site.css">
  {schema}
  <script>window.sa_event=window.sa_event||function(){{var a=[].slice.call(arguments);window.sa_event.q?window.sa_event.q.push(a):window.sa_event.q=[a]}};</script>
  <script async src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
  <script defer src="assets/site.js"></script>
</head>
<body data-page="{'thank-you' if name == 'thank-you.html' else current}">
  {header(current)}
  <main id="main">{body}</main>
  {footer() if name != 'thank-you.html' else ''}
</body>
</html>'''
    html = html.replace(" & ", " &amp; ")
    html = "\n".join(line.rstrip() for line in html.splitlines()) + "\n"
    (ROOT / name).write_text(html, encoding="utf-8")


home = '''
<section class="hero">
  <div class="container hero-grid">
    <div>
      <p class="eyebrow">Managed customer intake</p>
      <h1 class="display">Turn busy phone lines into a <span class="orange">reliable intake system.</span></h1>
      <p class="lede">We design, test, and manage AI front desks for service businesses—so callers can get approved answers, request appointments, leave complete job details, or reach the right person when your team is busy.</p>
      <div class="btn-row"><a class="btn btn-primary" href="contact.html" data-event="hero_pilot_click">Start a 14-day pilot — $750</a><a class="btn" href="ai-voice-agents.html" data-event="hero_voice_click">See how it works</a></div>
      <div class="trust-line"><span>Inbound-first</span><span>Approved scripts</span><span>Human fallback</span><span>Measured, not promised</span></div>
    </div>
    <div class="route-visual" role="img" aria-label="Illustration showing an inbound call routed through approved intake to the right next step">
      <div class="route-line" aria-hidden="true"></div><div class="route-diagram"><div class="route-node">01 · Caller reaches your line</div><div class="route-node">02 · AI disclosure + intake</div><div class="route-node">03 · Approved answer or qualification</div><div class="route-node">04 · Book · transfer · callback</div></div><span class="route-label">A bounded path—not an open-ended bot</span>
    </div>
  </div>
</section>
<section class="section rule">
  <div class="container"><div class="section-head"><div><p class="eyebrow">The operational gap</p><h2>Your office cannot always stop to answer.</h2></div><p class="lede">Crews are working. Dispatch is busy. The office closes. RouteCraft gives routine inbound calls a documented first response without turning AI into a wall between customers and your team.</p></div>
    <div class="grid-3">
      <article class="card"><h3>Respond beyond office hours</h3><p>Configure an approved first response for overflow and after-hours calls, subject to routing rules and platform availability.</p></article>
      <article class="card"><h3>Capture complete information</h3><p>Ask the same approved questions and send the team a structured summary instead of an incomplete voicemail.</p></article>
      <article class="card"><h3>Connect the next step</h3><p>Transfer, request or book an appointment, or hand off data to a supported calendar, CRM, field-service tool, email, or webhook.</p></article>
    </div>
  </div>
</section>
<section class="section section-dark">
  <div class="container"><p class="eyebrow">What we build</p><span class="kicker">One front door.<br><span class="orange">Three ways in.</span></span>
    <div class="grid-3">
      <article class="card card-dark"><span class="tag tag-orange">Launch offer</span><h3>AI Front Desk</h3><p>Managed inbound call handling with approved FAQs, structured intake, one standard integration, and human fallback.</p><a class="card-link" href="ai-voice-agents.html">Explore voice agents</a></article>
      <article class="card card-dark"><span class="tag">Digital foundation</span><h3>Website & Care</h3><p>A focused, responsive website with a clear conversion path, analytics, hosting, SSL, form delivery, and maintenance.</p><a class="card-link" href="web-development.html">Explore web development</a></article>
      <article class="card card-dark"><span class="tag">Combined system</span><h3>Connected Growth</h3><p>Website, phone intake, booking, follow-up, and supported integrations managed as one customer-intake system.</p><a class="card-link" href="services.html">Compare packages</a></article>
    </div>
  </div>
</section>
<section class="section">
  <div class="container"><div class="section-head"><div><p class="eyebrow">Delivery method</p><h2>Control the workflow before live traffic.</h2></div><p>We do not throw a prompt at your phone line. The launch process makes responsibilities, boundaries, tests, and fallbacks explicit.</p></div>
    <ol class="step-list"><li><span class="step-num">01</span><h3>Map</h3><p>Document call types, required fields, approved answers, routing, exceptions, and the human path.</p></li><li><span class="step-num">02</span><h3>Build</h3><p>Configure the voice, number, knowledge, calendar, and supported integration or handoff.</p></li><li><span class="step-num">03</span><h3>Test</h3><p>Run normal, edge, prohibited, and failure scenarios. Fix issues before your callers meet the system.</p></li><li><span class="step-num">04</span><h3>Launch</h3><p>Begin with overflow or after-hours traffic. Expand only after client acceptance and observed behavior.</p></li><li><span class="step-num">05</span><h3>Improve</h3><p>Review exceptions and approved outcomes monthly instead of treating total call count as success.</p></li></ol>
  </div>
</section>
<section class="section section-accent" id="pilot">
  <div class="container pilot-panel"><div><p class="eyebrow">Low-friction validation</p><div class="pilot-price">$750</div><h2>14-day AI Front Desk pilot.</h2><p class="lede">Prove one workflow's operational fit before a full deployment. This is a paid validation, not a free custom build.</p><a class="btn btn-dark" href="contact.html" data-event="home_pilot_apply">Check your fit</a></div><div><ul class="check-list"><li>One business, one location, one inbound flow</li><li>Up to 10 approved FAQs</li><li>One calendar connection or structured email handoff</li><li>Up to 100 connected live minutes</li><li>Up to 15 scripted scenarios before launch</li><li>Five-business-day build target after complete inputs</li><li>14 calendar days of overflow or after-hours use</li><li>End-of-pilot workflow and exception report</li></ul><p class="small"><strong>$500 production credit</strong> if the production agreement is signed within 10 calendar days after the pilot report. Full terms apply.</p></div></div>
</section>
<section class="section">
  <div class="container"><div class="section-head"><div><p class="eyebrow">Proof without theater</p><h2>Inspect the system, not invented success stories.</h2></div><p>A new agency should not manufacture client logos, testimonials, or ROI claims. We show how the workflow behaves and where it stops.</p></div>
    <div class="grid-2"><div class="call-sim section-dark"><div class="call-sim-head"><span>Simulated scenario</span><span>After-hours intake</span></div><div class="call-sim-body"><p class="bubble">My AC stopped cooling. Can someone come tonight?</p><p class="bubble agent">I’m an AI assistant helping with initial intake. I can collect the service address, contact details, and what you’re noticing, then follow the approved after-hours path. If there is smoke, fire, a gas odor, or immediate danger, contact emergency services now.</p><p class="bubble">No danger. The house is getting warm.</p><p class="bubble agent">Understood. First, what ZIP code is the service address in?</p></div></div><div><h3>What you can evaluate</h3><ul class="check-list"><li>Does the disclosure play at the approved point?</li><li>Are required fields captured consistently?</li><li>Do prohibited requests follow the refusal path?</li><li>Do human transfer and fallback paths work?</li><li>Does the calendar or handoff contain the agreed fields?</li><li>Are failures visible in the exception report?</li></ul><p class="small muted">Scenario is illustrative, not a live client call or performance claim.</p></div></div>
  </div>
</section>
<section class="section section-dark">
  <div class="container"><div class="section-head"><div><p class="eyebrow">Common questions</p><h2>What responsible automation sounds like.</h2></div><a class="btn" href="services.html#faq">See all FAQs</a></div>
    <div class="faq"><details><summary>Will callers know they are speaking with AI?</summary><div>Yes. RouteCraft workflows are designed to identify the assistant as AI at or near the start of the interaction.</div></details><details><summary>Can callers reach a person?</summary><div>The workflow can recognize a request for human help and use the approved fallback. Actual transfer availability and response times depend on the client's staffing and configuration.</div></details><details><summary>Does the agent diagnose HVAC, plumbing, or electrical problems?</summary><div>No. It is designed for administrative intake, not technical diagnosis, licensed advice, or emergency judgment.</div></details><details><summary>Do you guarantee more bookings?</summary><div>No. We guarantee the agreed implementation work and report what the system actually did. Demand, availability, offer quality, caller intent, and team follow-up all affect business outcomes.</div></details></div>
  </div>
</section>'''

services = '''
<section class="page-hero"><div class="container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a> / Services</nav><p class="eyebrow">Offers & pricing</p><h1 class="display">Customer-intake systems with <span class="orange">clear boundaries.</span></h1><p class="lede">Choose a focused AI front desk, a credible website foundation, or a connected system that brings phone and web intake together.</p></div></section>
<section class="section"><div class="container"><div class="price-grid">
  <article class="price-card featured"><span class="tag tag-orange">Primary offer</span><h3>AI Front Desk</h3><div class="price">$3,000 <small>setup + $850/month</small></div><p>For one service business location with repeatable inbound calls and a defined human escalation path.</p><ul><li>500 connected voice minutes</li><li>250 approved-workflow SMS</li><li>One number and one location</li><li>Up to three approved call flows</li><li>Up to 25 approved FAQs</li><li>One standard calendar connection</li><li>One standard integration or handoff</li><li>30+ scripted test scenarios</li><li>Monthly exception review and optimization batch</li></ul><p class="small muted">Typical implementation: 2–3 weeks after complete intake, access, and approvals.</p><a class="btn btn-primary" href="contact.html" data-event="price_ai_front_desk">Discuss AI Front Desk</a></article>
  <article class="price-card"><span class="tag">Website</span><h3>Foundation & Care</h3><div class="price">$4,500 <small>setup + $249/month</small></div><p>For a local service business that needs a credible conversion path before adding automation.</p><ul><li>Responsive website, up to 7 standard pages</li><li>One primary conversion path</li><li>Basic on-page SEO</li><li>Analytics and agreed conversion events</li><li>Contact form with spam protection</li><li>Hosting, SSL, monitoring, and backups</li><li>Accessibility and performance baseline review</li><li>Two small monthly content requests</li></ul><p class="small muted">Typical implementation: 3–4 weeks after complete inputs and access.</p><a class="btn" href="contact.html" data-event="price_website">Discuss your website</a></article>
  <article class="price-card"><span class="tag">Combined</span><h3>Connected Growth</h3><div class="price">$8,500 <small>setup + $1,750/month</small></div><p>For a service business that needs its website, phone intake, booking, and follow-up to operate as one managed system.</p><ul><li>Website up to 10 standard pages</li><li>Up to two locations and phone numbers</li><li>Up to five inbound call flows</li><li>Up to 50 approved FAQs</li><li>Up to two standard integrations</li><li>1,500 connected voice minutes</li><li>1,000 approved-workflow SMS</li><li>Website and voice analytics where available</li></ul><p class="small muted">Typical implementation: 5–7 weeks after complete inputs, access, and approvals.</p><a class="btn" href="contact.html" data-event="price_connected">Discuss Connected Growth</a></article>
</div><p class="small muted">All prices are USD launch prices and exclude taxes, paid media, premium domains, third-party licenses, telecom surcharges, and client-side software fees unless a proposal states otherwise. Recurring fees are prepaid monthly. Additional voice usage is $0.50 per connected minute and approved-workflow SMS overage is $0.05 each.</p></div></section>
<section class="section section-accent" id="pilot"><div class="container pilot-panel"><div><p class="eyebrow">Paid validation</p><div class="pilot-price">$750</div><h2>Start smaller.</h2><p class="lede">Validate one bounded inbound workflow over 14 live days before committing to production.</p></div><div><h3>Included</h3><ul class="check-list"><li>One temporary or forwarded number</li><li>One inbound flow and up to 10 FAQs</li><li>Calendar connection or structured email handoff</li><li>Up to 100 live connected minutes</li><li>Up to 15 scripted tests</li><li>End-of-pilot report</li></ul><h3>Not included</h3><p>Number porting, custom CRM writeback, outbound campaigns, multiple locations, multilingual service, payments, regulated data, emergency judgment, production SLA, or guaranteed business results.</p><p><strong>Commercial terms:</strong> paid in advance. Client approves the script, disclosures, routing, and tests before live use. $500 is credited toward a production setup fee if signed within 10 calendar days after the pilot report.</p><a class="btn btn-dark" href="contact.html" data-event="services_pilot_apply">Apply for the pilot</a></div></div></section>
<section class="section"><div class="container split"><div class="sticky-copy"><p class="eyebrow">Scope discipline</p><h2>When a custom quote is mandatory.</h2></div><div><ul class="check-list"><li>More than 2,500 voice minutes per month</li><li>More than two locations, numbers, integrations, or an additional language</li><li>Private APIs, write access to a system of record, or custom application UI</li><li>Outbound calling beyond a narrow warm-lead or customer workflow</li><li>Payments, identity verification, healthcare, legal, financial, minors', or other sensitive data</li><li>24/7 support, contractual uptime, SSO, DPA/BAA, data residency, or enterprise procurement</li><li>Compressed timelines, third-party minimums, or unusually complex approval structures</li></ul><div class="notice notice-warning"><strong>No silent scope expansion.</strong> If technical feasibility is uncertain, RouteCraft may recommend paid discovery before quoting implementation. If budget is constrained, scope is reduced rather than hidden.</div></div></div></section>
<section class="section section-dark" id="faq"><div class="container"><div class="section-head"><div><p class="eyebrow">Frequently asked</p><h2>Before you buy.</h2></div></div><div class="faq">
<details><summary>Can it book appointments?</summary><div>A calendar connection may be configured when appropriate. Availability, write behavior, confirmation rules, and platform compatibility are tested before launch. If reliable write access is unavailable, the system can request a preferred slot for staff confirmation.</div></details>
<details><summary>Which integrations do you support?</summary><div>Standard calendars, CRMs, field-service tools, email, SMS, and webhooks may be supported. Compatibility is reviewed before it is sold. An unsupported or private system requires discovery and a custom quote.</div></details>
<details><summary>Is the pilot free?</summary><div>No. It costs $750 and includes the defined 14-day scope. It is paid validation, not an open-ended free build.</div></details>
<details><summary>Do you guarantee uptime or revenue?</summary><div>No. RouteCraft does not guarantee uptime, bookings, revenue, search rankings, call quality, conversion lift, or caller satisfaction unless a signed agreement expressly states a specific service level.</div></details>
<details><summary>What happens if callers want a human?</summary><div>The approved fallback can transfer, collect a callback request, route to voicemail, or send a structured notification. Human staffing and response times remain the client's responsibility unless expressly included.</div></details>
<details><summary>What are the payment terms?</summary><div>Standard production setup fees are 60% at signature and 40% before production launch. Recurring fees are prepaid monthly. Pilot payment is due in full in advance. A quote is valid for 14 calendar days.</div></details>
</div></div></section>'''

voice = '''
<section class="page-hero"><div class="container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a> / AI Voice Agents</nav><p class="eyebrow">Inbound-first voice automation</p><h1 class="display">An AI front desk with an <span class="orange">exit path.</span></h1><p class="lede">Give callers a consistent first interaction based on your approved scripts, FAQs, service boundaries, and handoff rules—without pretending software should make every decision.</p><div class="btn-row"><a class="btn btn-primary" href="contact.html" data-event="voice_pilot_click">Start with the $750 pilot</a><a class="btn" href="services.html">View full scope</a></div></div></section>
<section class="section"><div class="container grid-2"><div><p class="eyebrow">Designed to handle</p><h2>Routine intake and the next administrative step.</h2><ul class="check-list"><li>Disclose that the caller is speaking with an AI assistant</li><li>Collect contact, address, job type, and urgency details</li><li>Answer only approved business FAQs</li><li>Check service-area or request-type fit using documented rules</li><li>Request or book an appointment where supported</li><li>Send a structured call summary</li><li>Trigger an approved inbound-workflow SMS</li><li>Transfer, take a message, or create a callback request</li></ul></div><div><p class="eyebrow">Not designed to handle</p><h2>Safety judgment or promises only your team can make.</h2><ul class="check-list"><li>Pretending to be a human</li><li>Diagnosing electrical, gas, HVAC, plumbing, or other safety issues</li><li>Replacing 911 or local emergency services</li><li>Making unapproved pricing or arrival-time commitments</li><li>Collecting unnecessary sensitive information</li><li>Binding estimates, payments, identity verification, or professional advice in the base scope</li><li>Cold consumer robocalling or purchased-list outreach</li><li>Continuing when the approved workflow requires escalation</li></ul></div></div></section>
<section class="section section-dark"><div class="container"><div class="section-head"><div><p class="eyebrow">Control model</p><h2>The team decides where automation ends.</h2></div><p>Each workflow starts with explicit business rules. Unknown, prohibited, urgent, or sensitive situations follow an approved refusal or human fallback path.</p></div><div class="grid-3"><article class="card card-dark"><h3>Approved knowledge</h3><p>Responses are limited to business information and FAQs your team reviews before launch.</p></article><article class="card card-dark"><h3>Scripted evaluation</h3><p>Normal, edge, refusal, transfer, and failure scenarios are tested before live calls.</p></article><article class="card card-dark"><h3>Exception review</h3><p>Monthly review focuses on failures and unclear calls—not vanity totals.</p></article></div></div></section>
<section class="section"><div class="container split"><div class="sticky-copy"><p class="eyebrow">Integrations</p><h2>Move the intake into the system your team uses.</h2><p>One standard integration or handoff is included in the base AI Front Desk, subject to compatibility review.</p></div><div><table class="data-table"><thead><tr><th>Destination</th><th>Typical action</th><th>Fallback</th></tr></thead><tbody><tr><td>Calendar</td><td>Request or book an approved slot</td><td>Capture preferred time for staff confirmation</td></tr><tr><td>CRM / field service</td><td>Create or update a structured inquiry where supported</td><td>Email or webhook handoff</td></tr><tr><td>Email</td><td>Send call summary and required fields</td><td>Secondary recipient or callback queue</td></tr><tr><td>SMS</td><td>Send approved confirmation from an inbound workflow</td><td>Email confirmation</td></tr><tr><td>Webhook</td><td>Post an agreed payload to a supported endpoint</td><td>Queue and notify on failure where supported</td></tr></tbody></table><p class="small muted">Third-party pricing, permissions, API limits, changes, and outages are outside RouteCraft's control. Unsupported/private systems require custom discovery.</p></div></div></section>
<section class="section section-accent" id="disclosure"><div class="narrow"><p class="eyebrow">AI, recording & safety disclosure</p><h2>Disclosure happens in the call—not just on this page.</h2><p class="lede">RouteCraft workflows are designed to identify the assistant as AI. If recording or transcription is enabled, the client must approve an audible notice and consent flow appropriate to every relevant jurisdiction.</p><div class="notice"><h3>Illustrative opening</h3><p>“Thanks for calling [Business Name]. I’m an AI assistant helping with initial call intake. I can collect a few details and help with the next step. If you prefer a person, please say ‘representative.’”</p><h3>If recording or transcription is enabled</h3><p>“This call may be recorded or transcribed for service, quality, and training purposes. By continuing, you acknowledge this notice. You may ask for another contact option.”</p></div><p><strong>Important:</strong> This language is illustrative, not legal advice. Consent rules vary by jurisdiction and participant location. Some jurisdictions require consent from all participants. Clients remain responsible for obtaining legal review, approving the final wording, maintaining a lawful alternative, and using recordings/transcripts only for approved purposes.</p><p>AI output can be incomplete, delayed, or incorrect. Voice recognition may be affected by accents, noise, connectivity, caller behavior, and upstream services. For fire, gas odor, electrical danger, flooding, injury, or immediate threats, callers should contact 911 or the appropriate local emergency service.</p></div></section>'''

web = '''
<section class="page-hero"><div class="container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a> / Web Development</nav><p class="eyebrow">Website Foundation & Care</p><h1 class="display">A service-business website built for <span class="orange">clear customer action.</span></h1><p class="lede">Explain what you do, where you work, and how customers should contact you—without burying the next step under generic agency theater.</p><div class="btn-row"><a class="btn btn-primary" href="contact.html" data-event="web_contact_click">Discuss your website</a><a class="btn" href="services.html">See $4,500 scope</a></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">What the foundation includes</p><h2>Launch essentials, managed together.</h2></div><p>The standard scope is intentionally bounded so the site can move from intake to production in roughly 3–4 weeks after content and access are complete.</p></div><div class="grid-3"><article class="card"><h3>Conversion path</h3><p>Up to seven responsive pages organized around one primary action: call, book, or submit a qualified inquiry.</p></article><article class="card"><h3>Technical foundation</h3><p>Titles, descriptions, headings, canonical URLs, sitemap, robots file, SSL, analytics, and agreed conversion events.</p></article><article class="card"><h3>Reliable operations</h3><p>Spam-protected form, tested delivery, hosting, monitoring, backups, CMS/security updates, and two small monthly content requests.</p></article></div></div></section>
<section class="section section-dark"><div class="container split"><div class="sticky-copy"><p class="eyebrow">Typical structure</p><h2>Every page has a job.</h2></div><div><ol class="step-list"><li><span class="step-num">01</span><h3>Home</h3><p>Position the business, identify the customer problem, and make the primary next step obvious.</p></li><li><span class="step-num">02</span><h3>Services</h3><p>Clarify scope, fit, exclusions, and the right path for each service type.</p></li><li><span class="step-num">03</span><h3>Proof</h3><p>Use verifiable work, process, credentials, or customer-approved evidence—never fabricated logos or testimonials.</p></li><li><span class="step-num">04</span><h3>About</h3><p>Show who is accountable, how the company works, and what it will not promise.</p></li><li><span class="step-num">05</span><h3>Contact</h3><p>Collect enough information to qualify the inquiry and set an honest response expectation.</p></li></ol></div></div></section>
<section class="section"><div class="container grid-2"><div><p class="eyebrow">Included boundaries</p><h2>What this package is.</h2><ul class="check-list"><li>One responsive marketing site, up to seven standard pages</li><li>Semi-custom visual system using approved brand assets</li><li>Client-supplied copy edited for clarity; light copywriting up to 2,500 words</li><li>One standard form/webhook connection</li><li>Accessibility and performance baseline review</li><li>One training session and launch checklist</li><li>Care plan with two small content requests per month</li></ul></div><div><p class="eyebrow">Explicit exclusions</p><h2>What it is not.</h2><ul class="check-list"><li>Full naming, logo, photography, video, or translation engagement</li><li>Ecommerce, membership, portals, custom calculators, or web applications</li><li>Ongoing SEO campaigns, link building, or paid media</li><li>Legal advice or bespoke policy drafting</li><li>Complex CRM or private API integrations</li><li>Guaranteed accessibility certification, speed score, rank, traffic, or leads</li><li>Unlimited revisions or unscoped custom development</li></ul></div></div></section>
<section class="section section-accent"><div class="container pilot-panel"><div><p class="eyebrow">Website Foundation & Care</p><div class="pilot-price">$4,500</div><h2>+$249/month.</h2></div><div><p class="lede">A professional launch plus ongoing care, not a file handoff that becomes your next maintenance problem.</p><p>Setup fees are 60% at signature and 40% before launch. Recurring fees are prepaid monthly. Extra work is $125/hour or a fixed change order. Standard usage assumes up to 25,000 page views per month and 10 GB storage.</p><a class="btn btn-dark" href="contact.html" data-event="web_package_click">Scope the website</a></div></div></section>'''

about = '''
<section class="page-hero"><div class="container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a> / About</nav><p class="eyebrow">About RouteCraft</p><h1 class="display">Small scope. Clear rules. <span class="orange">Managed implementation.</span></h1><p class="lede">RouteCraft Systems is a managed AI front desk and web development company founded by Praneeth Pogula. Based in India, we serve international service businesses with a launch focus on independent US HVAC, plumbing, and electrical operators.</p></div></section>
<section class="section"><div class="container split"><div class="sticky-copy"><p class="eyebrow">Why this wedge</p><h2>The first customer interaction is an operational system.</h2></div><div><p class="lede">A phone call is often attached to an urgent service request. Yet the person best equipped to answer may be dispatching, serving a customer, driving, or off the clock.</p><p>RouteCraft starts with overflow and after-hours intake because it is concrete, testable, and bounded. We map what the caller needs, what the business may safely say, which fields matter, and when a person must take over.</p><p>The goal is not to replace trade expertise or promise automatic growth. It is to create a more organized front door for callers and staff.</p></div></div></section>
<section class="section section-dark"><div class="container"><div class="section-head"><div><p class="eyebrow">Operating principles</p><h2>Trust comes from boundaries.</h2></div></div><div class="grid-3"><article class="card card-dark"><h3>Disclose the AI</h3><p>Callers should know when they are interacting with an automated assistant and have an appropriate alternative.</p></article><article class="card card-dark"><h3>Approve before launch</h3><p>Clients review scripts, FAQs, disclosures, routing, test results, and escalation rules before live traffic.</p></article><article class="card card-dark"><h3>Escalate judgment</h3><p>Unknown, prohibited, sensitive, or safety-related requests should not be improvised by the system.</p></article><article class="card card-dark"><h3>Measure behavior</h3><p>Success criteria focus on fields captured, routes followed, and exceptions found—not invented revenue attribution.</p></article><article class="card card-dark"><h3>Sell supported scope</h3><p>Integrations are promised only after compatibility review. Unsupported systems get a fallback or discovery phase.</p></article><article class="card card-dark"><h3>Keep a human path</h3><p>Transfer, callback, voicemail, or structured notification is defined for cases the system should not handle.</p></article></div></div></section>
<section class="section"><div class="container grid-2"><div><p class="eyebrow">Founder</p><h2>Praneeth Pogula</h2><p class="lede">Founder and systems builder focused on AI agents, web development, automation, and practical integrations.</p><p>RouteCraft is early-stage. That means this website does not display invented clients, testimonials, awards, or performance results. Prospects should evaluate the actual demo, test matrix, workflow design, scope, and pilot report.</p><a class="btn" href="mailto:praneethpogula09@gmail.com" data-event="founder_email_click">Email Praneeth</a></div><div class="notice"><h3>What we will say</h3><p>“Designed to,” “configured to,” “can,” “where supported,” and “measured during the pilot.”</p><h3>What we will not say</h3><p>“Never miss a call,” “guaranteed appointments,” “100% accurate,” “fully compliant,” “replaces your team,” or “works with every CRM.”</p></div></div></section>'''

contact = f'''
<section class="page-hero"><div class="container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a> / Contact</nav><p class="eyebrow">Qualified inquiry</p><h1 class="display">Tell us what happens when <span class="orange">nobody answers.</span></h1><p class="lede">Share the current call path, approximate volume, and system you use. We will review whether the $750 pilot or a production package is a sensible fit.</p></div></section>
<section class="section"><div class="container split"><aside class="contact-aside"><h3>Direct contact</h3><p><a href="mailto:{EMAIL}" data-event="contact_email_click">{EMAIL}</a></p><p class="small muted">Use email if the form or CAPTCHA is inaccessible. Do not send passwords, payment-card data, government identifiers, medical information, or other sensitive data.</p><h3>Strong pilot fit</h3><ul><li>HVAC, plumbing, or electrical business</li><li>One location to start</li><li>75+ inbound calls per month</li><li>Documented FAQs and escalation contact</li><li>Willing to start with overflow or after-hours</li></ul><h3>Not a fit</h3><ul><li>Cold consumer robocalling</li><li>Automated safety diagnosis</li><li>No human escalation path</li><li>Guaranteed booking or revenue expectation</li></ul></aside><div>
<form id="qualified-inquiry" action="https://formsubmit.co/{EMAIL}" method="POST">
  <input type="hidden" name="_subject" value="New qualified inquiry — RouteCraft Systems">
  <input type="hidden" name="_template" value="table">
  <input type="hidden" name="_captcha" value="true">
  <input type="hidden" name="_next" value="{ORIGIN}/thank-you.html">
  <div class="honeypot" aria-hidden="true"><label for="company-site">Leave this field empty</label><input id="company-site" type="text" name="_honey" tabindex="-1" autocomplete="off"></div>
  <div class="form-grid">
    <div class="field"><label for="name">Name <span class="required">*</span></label><input id="name" name="name" type="text" autocomplete="name" required></div>
    <div class="field"><label for="business">Business name <span class="required">*</span></label><input id="business" name="business_name" type="text" autocomplete="organization" required></div>
    <div class="field"><label for="email">Work email <span class="required">*</span></label><input id="email" name="email" type="email" autocomplete="email" required></div>
    <div class="field"><label for="phone">Phone</label><input id="phone" name="phone" type="tel" autocomplete="tel"></div>
    <div class="field"><label for="type">Business type <span class="required">*</span></label><select id="type" name="business_type" required><option value="">Choose one</option><option>HVAC</option><option>Plumbing</option><option>Electrical</option><option>Property management</option><option>Auto repair</option><option>Other service business</option></select></div>
    <div class="field"><label for="locations">Locations <span class="required">*</span></label><select id="locations" name="locations" required><option value="">Choose one</option><option>1</option><option>2</option><option>3–5</option><option>6+</option></select></div>
    <div class="field"><label for="volume">Approximate inbound calls/month <span class="required">*</span></label><select id="volume" name="monthly_inbound_calls" required><option value="">Choose one</option><option>Under 30</option><option>30–74</option><option>75–249</option><option>250–999</option><option>1,000+</option><option>Unknown</option></select></div>
    <div class="field"><label for="service">What are you considering? <span class="required">*</span></label><select id="service" name="service_interest" required><option value="">Choose one</option><option>$750 AI Front Desk pilot</option><option>AI Front Desk production</option><option>Website Foundation & Care</option><option>Connected Growth System</option><option>Not sure</option></select></div>
    <div class="field field-full"><label for="platform">Calendar, CRM, field-service, or job-management platform</label><input id="platform" name="current_platform" type="text" placeholder="For example: Google Calendar, ServiceTitan, Jobber, Housecall Pro"></div>
    <div class="field field-full"><label for="website">Current website</label><input id="website" name="current_website" type="url" inputmode="url" placeholder="https://"></div>
    <div class="field field-full"><label for="problem">What happens today when staff cannot answer? <span class="required">*</span></label><textarea id="problem" name="intake_problem" required></textarea></div>
    <div class="field field-full"><label for="contact-method">Preferred reply method</label><select id="contact-method" name="preferred_contact_method"><option>Email</option><option>Phone</option></select></div>
    <div class="field field-full checkbox"><input id="consent" name="privacy_consent" type="checkbox" value="Agreed" required><label for="consent">I agree that RouteCraft Systems may use this information to respond to my inquiry under the <a href="privacy.html">Privacy Policy</a>. I understand that submitting this form does not create a client relationship or guarantee project acceptance. <span class="required">*</span></label></div>
  </div>
  <div class="form-actions"><button class="btn btn-primary" type="submit">Submit qualified inquiry</button></div>
  <p class="small muted">Protected by FormSubmit's CAPTCHA and honeypot controls. Form data is sent to RouteCraft's email provider through FormSubmit. See the Privacy Policy for details.</p>
</form>
</div></div></section>'''

privacy = f'''
<section class="page-hero"><div class="narrow"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a> / Privacy</nav><p class="eyebrow">Legal</p><h1 class="display">Privacy policy.</h1><p class="lede">Last updated: {UPDATED}</p></div></section>
<section class="section"><div class="narrow prose"><div class="legal-note"><strong>Plain-language summary:</strong> We collect the information you choose to submit so we can respond to business inquiries. Simple Analytics records privacy-friendly page and event data without cookies. Do not submit sensitive information through this website.</div>
<h2>1. Who we are</h2><p>RouteCraft Systems is a managed AI front desk and web development business operated by Praneeth Pogula, based in India and serving clients internationally. Privacy questions and requests may be sent to <a href="mailto:{EMAIL}">{EMAIL}</a>.</p>
<h2>2. Information we collect</h2><h3>Information you provide</h3><p>When you contact us, we may collect your name, business name, work email, phone number, business type, locations, approximate call volume, current website, systems used, service interest, message, preferred contact method, and consent record.</p><h3>Website usage data</h3><p>We use Simple Analytics to collect privacy-friendly page views and named conversion events such as CTA clicks and form-submission attempts. The deployed configuration does not use cookies, fingerprint visitors, create cross-site profiles, or intentionally send form-field values to analytics. Simple Analytics may process URL, referrer, viewport, user agent, country derived from an IP address, timestamp, and event names as described in its own documentation.</p>
<h2>3. How we use information</h2><ul><li>Respond to inquiries and evaluate project fit</li><li>Prepare proposals or arrange a discovery conversation</li><li>Operate, secure, troubleshoot, and improve this website</li><li>Measure aggregate site activity and conversion events</li><li>Comply with legal obligations and protect our rights</li></ul><p>Submitting an inquiry does not subscribe you to bulk marketing. Separate consent may be requested for marketing, SMS, or automated calls where required.</p>
<h2>4. Service providers and international processing</h2><p>This site is hosted through GitHub Pages, a Microsoft-owned service. Inquiry forms are processed by FormSubmit and delivered through email providers. Website analytics are processed by Simple Analytics. These providers may process data in countries different from yours under their own privacy terms. Future client systems may also use telephony, speech, AI, messaging, calendar, CRM, hosting, and integration providers disclosed in the relevant agreement.</p>
<h2>5. Retention</h2><p>Inquiry records are retained only as long as reasonably needed to respond, manage a possible business relationship, resolve disputes, meet accounting or legal obligations, and maintain suppression or consent records where applicable. We may delete clearly irrelevant or abandoned inquiries. Client-project retention is governed by the applicable agreement and workflow.</p>
<h2>6. Security</h2><p>We use reasonable administrative and technical safeguards appropriate to a small service business, but no internet transmission, email system, or third-party platform is completely secure. Do not send passwords, payment-card data, government identifiers, medical information, or other sensitive personal data through the website form.</p>
<h2>7. AI calls, recordings, and client data</h2><p>RouteCraft designs systems for clients that may use AI-generated speech and, where enabled, recording or transcription. Clients control the purpose of their call workflows and remain responsible for approved disclosures, consent, lawful use, and accurate business content. RouteCraft may act as a service provider or processor for client-controlled information. People seeking rights regarding a client's call may need to contact that client directly.</p>
<h2>8. Your choices and rights</h2><p>Depending on your location, you may have rights to request access, correction, deletion, restriction, objection, portability, or information about processing. These rights may be subject to identity verification and legal exceptions. Send requests to <a href="mailto:{EMAIL}">{EMAIL}</a>. If we hold data only for a client, we may direct the request to that client.</p>
<h2>9. Children</h2><p>This website and our business services are intended for organizations and are not directed to children under 13. We do not knowingly collect personal information from children through this site.</p>
<h2>10. External links and policy updates</h2><p>External sites have their own privacy practices. We may update this policy as services, vendors, or legal obligations change. The revised version will be posted here with a new effective date.</p>
<h2>11. Contact</h2><p><strong>RouteCraft Systems</strong><br>Operator: Praneeth Pogula<br>Based in India; serving clients internationally<br>Email: <a href="mailto:{EMAIL}">{EMAIL}</a></p>
<div class="legal-note"><strong>Legal review notice:</strong> This policy is a good-faith launch disclosure, not a substitute for advice from qualified counsel. Recording consent, telemarketing, SMS, privacy, data-transfer, and client-contract requirements must be reviewed for the actual jurisdictions, vendors, and workflows used.</div></div></section>'''

terms = f'''
<section class="page-hero"><div class="narrow"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a> / Terms</nav><p class="eyebrow">Legal</p><h1 class="display">Website terms.</h1><p class="lede">Last updated: {UPDATED}</p></div></section>
<section class="section"><div class="narrow prose"><p>These Terms govern use of the RouteCraft Systems website. By using the website, you agree to these Terms. If you do not agree, do not use the website.</p>
<h2>1. Informational purpose</h2><p>Website content is provided for general business and informational purposes. It is not legal, tax, accounting, safety, technical, or other professional advice. Service descriptions, prices, timelines, and package details are summaries and may change. A project begins only after the parties sign an applicable agreement or order form.</p>
<h2>2. No client relationship from website use</h2><p>Visiting the site, submitting a form, or exchanging preliminary messages does not create a client, agency, fiduciary, partnership, employment, or other professional relationship.</p>
<h2>3. Paid client services</h2><p>Paid services are governed by the signed proposal, order form, statement of work, master services agreement, or other client agreement. If website content conflicts with a signed agreement, the signed agreement controls. Timelines begin only after required payment, intake, content, access, and approvals are complete.</p>
<h2>4. Acceptable use</h2><p>You may not attempt unauthorized access, disrupt the site, transmit malware, submit unlawful or deceptive material, misrepresent your authority, scrape or overload the site, or violate another person's rights.</p>
<h2>5. Intellectual property</h2><p>The site's original text, design, branding, graphics, and materials are owned by or licensed to RouteCraft unless stated otherwise. You may evaluate the site for legitimate business purposes but may not reproduce, sell, publish, or create derivative works from its content without permission. Third-party names, marks, and services belong to their owners; references do not imply partnership or endorsement.</p>
<h2>6. AI and automated systems</h2><p>AI and automated services can produce incorrect, incomplete, delayed, or unexpected results. Demonstrations and scenarios are illustrative and do not guarantee equivalent performance in a client's environment. RouteCraft does not provide emergency response, licensed trade diagnosis, legal advice, or guaranteed human availability through this website.</p>
<h2>7. Third-party services</h2><p>The site and RouteCraft services may depend on third-party hosting, telephony, speech, AI, messaging, calendar, analytics, form, email, payment, or integration providers. RouteCraft is not responsible for third-party content, policies, outages, changes, pricing, or acts outside its reasonable control.</p>
<h2>8. No guarantees</h2><p>To the fullest extent permitted by law, the website is provided “as is” and “as available.” RouteCraft does not guarantee uninterrupted access, error-free operation, bookings, revenue, rankings, lead volume, conversion results, cost savings, call quality, or any particular business outcome. Nothing in these Terms excludes a right or warranty that cannot lawfully be excluded.</p>
<h2>9. Limitation of liability</h2><p>To the fullest extent permitted by law, RouteCraft will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages arising from use of, or inability to use, the website. Liability relating to paid client services is governed by the applicable signed agreement. Some jurisdictions do not allow certain limitations, so these provisions may not apply in full.</p>
<h2>10. Indemnity</h2><p>To the extent permitted by law, you are responsible for claims arising from your unlawful misuse of the site or violation of these Terms. Client-service indemnity obligations, if any, are stated only in the applicable signed agreement.</p>
<h2>11. Changes and disputes</h2><p>We may update the site or these Terms. Updated Terms become effective when posted unless law requires otherwise. The governing law, venue, and dispute process for paid services will be stated in the applicable client agreement. Website disputes should be reviewed under laws applicable to RouteCraft's principal place of business unless mandatory law requires a different result.</p>
<h2>12. Contact</h2><p><strong>RouteCraft Systems</strong><br>Email: <a href="mailto:{EMAIL}">{EMAIL}</a></p>
<div class="legal-note"><strong>Legal review notice:</strong> These are launch-stage website terms, not legal advice. Formal client agreements and jurisdiction-specific review remain required before accepting paid work.</div></div></section>'''

thank_you = '''
<section class="section section-dark center-stage"><div class="narrow center-copy"><p class="eyebrow">Inquiry submitted</p><h1 class="display">The next step is <span class="orange">human.</span></h1><p class="lede">Thank you. RouteCraft will review the workflow details and reply using your preferred contact method. Submitting the form does not guarantee acceptance or create a client relationship.</p><div class="btn-row center-actions"><a class="btn btn-primary" href="index.html">Return home</a><a class="btn" href="mailto:praneethpogula09@gmail.com">Email directly</a></div></div></section>'''

not_found = '''
<section class="section section-dark center-stage"><div class="narrow center-copy"><p class="eyebrow">404 · Route not found</p><h1 class="display">This path has <span class="orange">no handoff.</span></h1><p class="lede">The page may have moved or the address may be incorrect.</p><div class="btn-row center-actions"><a class="btn btn-primary" href="index.html">Return home</a><a class="btn" href="contact.html">Contact RouteCraft</a></div></div></section>'''

page("index.html", "RouteCraft Systems | Managed AI Front Desks for Service Businesses", "Managed AI front desks, websites, and integrations for HVAC, plumbing, and electrical businesses. Start with a 14-day, $750 inbound pilot.", "home", home)
page("services.html", "Services & Pricing | RouteCraft Systems", "Compare RouteCraft's AI Front Desk, Website Foundation, Connected Growth, and $750 paid pilot for service businesses.", "services", services)
page("ai-voice-agents.html", "AI Voice Agents for Home Services | RouteCraft Systems", "Inbound AI phone intake with approved scripts, structured summaries, supported integrations, human fallback, and transparent disclosure.", "voice", voice)
page("web-development.html", "Service Business Website Development | RouteCraft Systems", "Responsive, conversion-focused websites with SEO foundations, analytics, lead capture, hosting, SSL, and ongoing care.", "web", web)
page("about.html", "About RouteCraft Systems | Practical AI Intake", "RouteCraft Systems, founded by Praneeth Pogula, builds bounded AI front desks and websites for international service businesses.", "about", about)
page("contact.html", "Contact RouteCraft Systems | Check Pilot Fit", "Submit a qualified inquiry for RouteCraft's $750 AI Front Desk pilot, production voice systems, or website packages.", "contact", contact)
page("privacy.html", "Privacy Policy | RouteCraft Systems", "How RouteCraft Systems handles website inquiries, analytics, service-provider data, AI calls, recordings, and privacy requests.", "legal", privacy)
page("terms.html", "Website Terms | RouteCraft Systems", "Terms governing the RouteCraft Systems website, service summaries, AI limitations, third-party services, and liability.", "legal", terms)
page("thank-you.html", "Inquiry Submitted | RouteCraft Systems", "RouteCraft Systems has received your inquiry for review.", "contact", thank_you, noindex=True)
page("404.html", "Page Not Found | RouteCraft Systems", "The requested RouteCraft Systems page could not be found.", "404", not_found, noindex=True)
print("Built 10 HTML pages")
